### ISSUE TITLE
Transmittance as models

### ISSUE THREAD

**Issue by pllim** [bmorris3/tynt#1]
https://github.com/bmorris3/tynt/blob/ae2dddfc58821d5daa18a2cbd52016d28c854ba4/tynt/core.py#L56-L62

But how to represent this as analytical Astropy models?

**Comment by bmorris3** [comment]
I was envisioning using lookup tables, which may have a performance penalty, but allows for _much_ more flexible model shapes.

**Comment by pllim** [comment]
I was thinking more like a custom analytical model. That way, `transmittance` is only evaluated on-the-fly, instead of a sampled model.

**Comment by bmorris3** [comment]
I'm pretty sure the discrete Fourier transform can be described with a custom analytical model which is a combination of sinusoids... I'll put investigating this on my todo list 😄

**Comment by eteq** [comment]
I agree with @pllim here.  Actually I think it's really easy - I'll try to whip up a quick PR to do that

**Comment by eteq** [comment]
Ok it's not quite as easy as I thought due to the variable-number-of-parameters problem (so I don't have time right now), but should still be doable: gist is that `reconstruct` could yield a *model*, with the class being something sort of like the existing polynomial models that have variable numbers of parameters (for the fourier coefficients).  Then the user can carry that model around instead of the `Filter` object.

Similarly `download_true_transmittance` would yield a `http://docs.astropy.org/en/stable/modeling/index.html#astropy.modeling.tabular.Tabular1D` (which I *think* supports units a la #4?  But if not it could be a similar custom model)

**Comment by bmorris3** [comment]
[Code updated to produce astropy models!](https://github.com/bmorris3/tynt/blob/master/tynt/core.py#L70-L111). It took three days of thinking about Fourier transforms to figure out how to make it work, but here we are. See [docs here](https://tynt.readthedocs.io/en/latest/gettingstarted.html#constructing-an-astropy-model-transmittance-curve). Ready for code review by @pllim, @eteq.

**Comment by pllim** [comment]
Hmm...

https://github.com/bmorris3/tynt/blob/e1f2f5f6ecba4dd192db1c30e84db1586c55aa03/tynt/core.py#L101-L102

What is the reason to keep both the sampled data *and* the model?

**Comment by bmorris3** [comment]
The idea was to make the API work like this: 

https://tynt.readthedocs.io/en/latest/gettingstarted.html#constructing-an-astropy-model-transmittance-curve

where the same object `Filter` would be returned whether or not you wanted the astropy model. Does that make sense?

**Comment by pllim** [comment]
> Does that make sense?

Not quite. If I have the model, why would I want to carry around the sampled values (extra memory footprint)? I can evaluate the model anytime to get them, no?

**Comment by bmorris3** [comment]
Understood. From my perspective, the whole point of the package is that the memory footprint of carrying around the simplified filter curves is _so small_, so I didn't see the problem with carrying around a few complex numbers. I see your point though, it could make a substantial runtime difference in Monte Carlo applications.

**Comment by bmorris3** [comment]
The latest tynt still offers an attribute for [producing astropy model representations](https://tynt.readthedocs.io/en/latest/api/tynt.FilterGenerator.html#tynt.FilterGenerator.reconstruct) of the filter without evaluating the transmittance at specific wavelengths, in case we ever want that. There's also a [convenience attribute `table`](https://tynt.readthedocs.io/en/latest/api/tynt.Filter.html#tynt.Filter.table) which returns a representation of the transmittance curve with an instance of `astropy.modeling.tabular.Tabular1D`, in case you want to rely on a strictly tabular model. 

Since (1) I think the above means your feature request has been implemented, and (2) I wrote tynt to do quickly provide the user with approximate transmittance curves, I'm going to close this issue as resolved. Thanks!
